name: Build
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of the Docker Image"
    required: false
    default: "academy"
  tag_name:
    description: "Tag for the Docker image"
    required: false

runs:
  using: composite
  steps:
    - name: "Define env variables"
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        
        echo "NAME=${{ inputs.image_name }}:$TAG" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV

        docker build . --file "${{ inputs.dockerfile_path }}" --tag $NAME
      shell: bash
