name: Build
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of the Docker Image"
    required: false
    default: "academy"
  tag_name:
    description: "Tag for the Docker image"
    required: false

runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          TAG=$(date +%s)
        else
          TAG=${{ inputs.tag_name }}
        fi
        
        NAME="${{ inputs.image_name }}:$TAG"
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
        
        docker build . --file "${{ inputs.dockerfile_path }}" --tag "$NAME"
      shell: bash
