name: Push
description: Push Docker image to Docker Hub
inputs:
  docker_username:
    description: "Docker username"
    required: true
  docker_token:
    description: "Docker token"
    required: true
  docker_image_name:
    description: "Docker Image Name"
    required: false
    default: $NAME:$TAG

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Docker Tag
      run: docker tag ${{ inputs.docker_image_name }} ${{inputs.docker_username}}/${{inputs.docker_image_name}}
      shell: bash

    - name: Docker Push
      run: docker push ${{inputs.docker_username}}/${{inputs.docker_image_name}}
      shell: bash

